#! /usr/bin/env python

bld.new_task_gen(
      features = 'qt4 cprogram cxx',
      source   = bld.glob('*.cpp'),
      target   = 'practica3',
      include  = '.',
      uselib   = ['QTCORE',
                  'QTGUI',
                  'QTOPENGL'],
      install_path = None)
